<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.csproj"/>
        <ProjectReference Include="..\Iam.Application.Abstractions\Iam.Application.Abstractions.csproj"/>
        <ProjectReference Include="..\Iam.Domain\Iam.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Register\"/>
    </ItemGroup>

</Project>
