<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>ContentEntries.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.csproj"/>
        <ProjectReference Include="..\ContentEntries.Application.Abstractions\ContentEntries.Application.Abstractions.csproj"/>
        <ProjectReference Include="..\ContentEntries.Core\ContentEntries.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.86"/>
        <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.12"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12"/>
        <PackageReference Include="SqlKata" Version="4.0.1"/>
        <PackageReference Include="SqlKata.Execution" Version="4.0.1"/>
    </ItemGroup>

</Project>
