<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.csproj"/>
        <ProjectReference Include="..\ContentTypes.Core\ContentTypes.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
    </ItemGroup>

</Project>
