// <auto-generated />
using System;
using ContentTypes.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContentTypes.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ContentTypes.Core.ContentField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ContentTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_content_fields");

                    b.HasIndex("ContentTypeId")
                        .HasDatabaseName("ix_content_fields_content_type_id");

                    b.ToTable("content_fields", (string)null);
                });

            modelBuilder.Entity("ContentTypes.Core.ContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_content_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_content_types_name");

                    b.ToTable("content_types", (string)null);
                });

            modelBuilder.Entity("ContentTypes.Core.ContentField", b =>
                {
                    b.HasOne("ContentTypes.Core.ContentType", null)
                        .WithMany("Fields")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_fields_content_types_content_type_id");
                });

            modelBuilder.Entity("ContentTypes.Core.ContentType", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
